application: sound-swap
version: 1
runtime: python
api_version: 1

handlers:
- url: /css
  static_dir: static/css
- url: /res
  static_dir: static/res
- url: /api/.*
  script: main.py
  # login: required
- url: .*
  script: main.py
